### ISSUE TITLE
Abusive content-length checking in case of compressed content

### ISSUE THREAD

**Issue by CoRfr** [rubysl/rubysl-xmlrpc#1]
Hi,

in the do_rpc function, there is a check on the expected size vs Content-Length.
The problem is that by default, net/http seems to for compressed content (Accept-Encoding => gzip).
In that case, Content-Length header reflects size of the compressed content, and not uncompressed content.

Since the decompression is managed by net/http, the Content-Length header doesn't match the length of data, and there was no Transfer-Encoding header.

date = Mon, 21 Sep 2015 21:16:56 GMT
server = Apache/2.2.22 (Ubuntu)
vary = Accept-Encoding
content-length = 945
connection = close
content-type = text/xml; charset=utf-8

Not sure what the best approach is, check that expected is >= Content-Length ? Use vary ?

**Comment by YorickPeterse** [comment]
Since we just vendor code from the MRI standard library its best to report any bugs/etc to bugs.ruby-lang.org unless they are specific to any support code we might add.
